name=MP6602
version=1.0.0
author=Pololu
maintainer=Pololu <inbox@pololu.com>
sentence=MP6602 stepper motor driver library for Arduino
paragraph=This is a library for the Arduino IDE that helps interface with the MP6602 stepper motor driver.
category=Device Control
url=https://github.com/pololu/mp6602-arduino
architectures=*
